title: "Nneka Asuzu"
description: "Data Scientist"
baseurl: "" 
url: "https://nnekaasuzu.github.io/"

author:
  name: "Nneka Asuzu"
  github: "https://github.com/NnekaAsuzu"
  linkedin: "https://www.linkedin.com/in/nneka-asuzu/"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation (order controlled by nav_order in each page's front matter)
navigation:
  - title: Home
    url: /index/
  - title: About Me
    url: /about/
  - title: Projects
    url: /projects/
  - title: Education
    url: /education/
  - title: Resume
    url: /resume/
  - title: Contact
    url: /contact/







