# Site settings
title: "Nneka Asuzu"
description: "Data Scientist | ML Professional | SQL & Python"
baseurl: "" # leave blank for user/organization sites
url: "https://nnekaasuzu.github.io/"

author:
  name: "Nneka Asuzu"
  github: "https://github.com/NnekaAsuzu"
  linkedin: "https://www.linkedin.com/in/nneka-asuzu/"

# GitHub Pages theme
theme: jekyll-theme-architect

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
navigation:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Education
    url: /education/
  - title: Resume
    url: /resume/
  - title: Contact
    url: /contact/




