title: "Nneka Asuzu"
description: "Data Scientist | ML Professional | SQL & Python"
baseurl: ""
url: "https://nnekaasuzu.github.io/"

author:
  name: "Nneka Asuzu"
  github: "https://github.com/NnekaAsuzu"
  linkedin: "https://www.linkedin.com/in/NnekaAsuzu"

remote_theme: pages-themes/architect@latest

plugins:
  - jekyll-feed
  - jekyll-seo-tag

navigation:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Education
    url: /education/
  - title: Resume
    url: /resume/
  - title: Contact
    url: /contact/



