title: "Nneka Asuzu"
description: "Data Scientist"
baseurl: ""
url: "https://nnekaasuzu.github.io/"

author:
name: "Nneka Asuzu"
github: "https://github.com/NnekaAsuzu"
linkedin: "https://www.linkedin.com/in/nneka-asuzu/"

theme: minima

plugins:
- jekyll-feed
- jekyll-seo-tag

# Navigation menu(excluding Home/index.md)
header_pages:
- about.md
- projects.md
- education.md
- resume.md
- contact.md

# Optional: SASS style (you can keep or remove)

sass:

  style: compressed



# Automatically include custom CSS on all pages

defaults:

  - scope:

      path: ""   # applies to all pages and posts

    values:

      head: "{% include head-custom.html %}"



