title: "Nneka Asuzu"
description: "Data Scientist"
baseurl: ""
url: "https://nnekaasuzu.github.io/"

author:
  name: "Nneka Asuzu"
  github: "https://github.com/NnekaAsuzu"
  linkedin: "https://www.linkedin.com/in/nneka-asuzu/"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation is controlled by nav_order in each page front matter







