title: "Welcome! I’m Nneka Asuzu"
description: "Data Scientist"
baseurl: ""
url: "https://nnekaasuzu.github.io/"

author:
  name: "Nneka Asuzu"
  github: "https://github.com/NnekaAsuzu"
  linkedin: "https://www.linkedin.com/in/nneka-asuzu/"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - projects.md
  - education.md
  - resume.md
  - contact.md

